version: 2

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

# Whether to enable the size reporting or not.
report_sizes: true

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    # ensures mod timestamp to be the commit timestamp
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X {{ .ModulePath }}/version.Version={{.Version}} -X {{ .ModulePath }}/version.BuildDate={{ .Date}} -X {{ .ModulePath }}/version.GitCommit={{.ShortCommit}}
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

    format_overrides:
      - goos: windows
        formats: ["zip"]

dockers_v2:
  - id: standard
    images:
      - "ghcr.io/mpapenbr/{{ .ProjectName }}"
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.source: "https://{{ .ModulePath }}"
      org.opencontainers.image.url: "https://{{ .ModulePath }}"
      org.opencontainers.image.description: "Dummy package for GHA tests"
      org.opencontainers.image.licenses: "Apache-2.0"
      description: "Some description"
      maintainer: "me@localhost"
    annotations:
      "index:org.opencontainers.image.description": "Dummy package for GHA tests"
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: true
    extra_files:
      - "ext/healthcheck"

  - id: web
    images:
      - "ghcr.io/mpapenbr/{{ .ProjectName }}-web"
    dockerfile: Dockerfile.nginx
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.source: "https://{{ .ModulePath }}"
      org.opencontainers.image.url: "https://{{ .ModulePath }}"
      org.opencontainers.image.description: "Simple web server"
      org.opencontainers.image.licenses: "Apache-2.0"
      description: "Some description"
      maintainer: "me@localhost"
    annotations:
      "index:org.opencontainers.image.description": "Simple web server"
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: true
    extra_files:
      - nginx/config
      - nginx/content

sboms:
  - artifacts: archive

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes" # needed on cosign 2.0.0+
    artifacts: checksum
    output: true

# signs our docker image
# https://goreleaser.com/customization/docker_sign
docker_signs:
  - cmd: cosign
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes"

release:
  prerelease: auto
  footer: |
    ---
    _Released with [GoReleaser](https://goreleaser.com)!_
